name: Deploy Azure Resources

on:
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy resources using Bicep
      uses: azure/cli@v1
      with:
        inlineScript: |
          az deployment group create --resource-group ${{ vars.AZURE_RG }} --template-file config/main.bicep --parameters namePrefix=${{ vars.AZURE_PREFIX }}
