name: Continuous Deployment to Azure

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay un push al branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1.5.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Deploy Docker Image
      env:
        AZURE_CONTAINER_REGISTRY: ${{vars.AZURE_PREFIX}}acr
        AZURE_CONTAINER_APP: ${{vars.AZURE_PREFIX}}containerapp
      run: |
        # Construye la imagen de Docker
        docker build -t $AZURE_CONTAINER_REGISTRY.azurecr.io/$AZURE_CONTAINER_APP:latest .

        # Login a Azure Container Registry
        az acr login --name $AZURE_CONTAINER_REGISTRY

        # Subir la imagen a ACR
        docker push $AZURE_CONTAINER_REGISTRY.azurecr.io/$AZURE_CONTAINER_APP:latest

        # Actualizar la Azure Container App con la nueva imagen
        az containerapp update --name $AZURE_CONTAINER_APP --resource-group ${{ vars.AZURE_RG }} --image $AZURE_CONTAINER_REGISTRY.azurecr.io/$AZURE_CONTAINER_APP:latest
